on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run the Action
      id: hello 
      uses: ./
      with:
      myinput: "Alexander Horning'
    - name: output
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "Total memory successfully output"
